WITH POPULAR AS (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)
SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES 
FROM REST_INFO AS R, POPULAR AS P 
WHERE R.FOOD_TYPE = P.FOOD_TYPE AND R.FAVORITES = P.MAX_FAVORITES
GROUP BY 1
ORDER BY 1 DESC