SELECT YEAR(SALES_DATE),MONTH(SALES_DATE),
    COUNT(DISTINCT U.USER_ID),
    ROUND((COUNT(DISTINCT U.USER_ID)/(SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED)=2021)),1)
FROM USER_INFO U INNER JOIN ONLINE_SALE O ON U.USER_ID = O.USER_ID
WHERE YEAR(JOINED)=2021
GROUP BY 1,2
ORDER BY 1,2